# Generated by Django 4.2.1 on 2026-01-15 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Vertical Head", "Vertical Head"),
                    ("Leadership", "Leadership"),
                    ("Auditor", "Auditor"),
                    ("Site Admin", "Site Admin"),
                ],
                default="Auditor",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[("VERTICAL", "Vertical"), ("DOMAIN", "Domain"), ("SUB_DOMAIN", "Sub Domain")],
                        max_length=20,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="user_management.unit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="user_management.unit",
            ),
        ),
    ]
