# Generated by Django 4.2.1 on 2026-01-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_user_role_unit_user_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Vertical Head', 'Vertical Head'), ('HoD', 'HoD'), ('HoS', 'HoS'), ('Auditor', 'Auditor'), ('Site Admin', 'Site Admin')], default='Auditor', max_length=20),
        ),
    ]
