# Generated by Django 5.2.10 on 2026-01-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0004_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="employee_id",
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_change_required",
            field=models.BooleanField(default=True),
        ),
    ]
