# Generated by Django 4.2.5 on 2024-04-07 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redflags',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='redflags',
            name='manuals',
        ),
        migrations.RemoveField(
            model_name='redflags',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='redflags',
            name='username',
        ),
        migrations.AddField(
            model_name='redflags',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redflags',
            name='lastrun',
            field=models.DateField(blank=True, null=True),
        ),
    ]
