# Generated by Django 4.2.6 on 2024-05-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interface", "0003_alter_redflags_options_alter_redflags_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="redflags",
            name="manual",
            field=models.FileField(blank=True, null=True, upload_to="manuals/"),
        ),
    ]
