# Generated by Django 4.2.6 on 2024-05-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0005_uploadedfile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadedFile",
        ),
    ]
