# Generated by Django 5.2.10 on 2026-01-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0007_remove_redflags_description_redflags_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redflags",
            name="category",
            field=models.CharField(
                choices=[("Red Flag", "Red Flag"), ("Audit Exceptions", "Audit Exceptions")], max_length=30
            ),
        ),
    ]
