# Generated by Django 5.2.10 on 2026-01-17 17:12

from django.db import migrations, models

import interface.validators


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0009_alter_redflags_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redflags",
            name="manual",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="manuals/",
                validators=[interface.validators.validate_file_extension, interface.validators.validate_file_size],
            ),
        ),
    ]
