# Generated by Django 5.2.10 on 2026-01-17 17:38

import django.db.models.deletion
import interface.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interface", "0010_alter_redflags_manual"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Automation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[("Automation", "Automation"), ("Exceptions", "Exceptions")], max_length=30
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("lastrun", models.DateTimeField(blank=True, null=True)),
                (
                    "manual",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="manuals/",
                        validators=[
                            interface.validators.validate_file_extension,
                            interface.validators.validate_file_size,
                        ],
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.DeleteModel(
            name="redflags",
        ),
    ]
