# Generated by Django 5.2.10 on 2026-01-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interface", "0011_automation_delete_redflags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automation",
            name="category",
            field=models.CharField(choices=[("Red Flag", "Red Flag"), ("Exceptions", "Exceptions")], max_length=30),
        ),
    ]
